### ISSUE TITLE
SEVERE: Exception starting filter struts2 java.lang.ClassNotFoundException: org.apache.struts2.dispatcher.ng.filter.StrutsPrepareAndExecuteFilter

### ISSUE THREAD

**Issue by dualboot** [chrishulbert/JavaTutorial#1]
I am using Java1.6SE with Eclipse Helios IDE. My Struts2 core version is 2.2.3. My Tomcat version is 7.0. My Sitemesh version is 2.4.1.

I am pretty much stuck on page 24.  I have Tomcat version 7 and the tutorial has 6. Is that code compatible with 7? 

Thank you

**Comment by chrishulbert** [comment]
I'd recommend tomcat 6, however tomcat 7 should work with a bit of fiddling.
Double check your struts jar's in your classpath and your app's lib folder
to solve the class not found exception.
Good luck

**Comment by dualboot** [comment]
Thank you for the response, I have not able to get that classpath error after copying the jar files into lib directory. Now the issue I am getting is 
Hibernate: select event0_.id as id0_, event0_.name as name0_ from TESTSCHEMA.Event event0_
672078 ["http-bio-8080"-exec-2] WARN  org.hibernate.util.JDBCExceptionReporter  - SQL Error: -1, SQLState: 42X05
672078 ["http-bio-8080"-exec-2] ERROR org.hibernate.util.JDBCExceptionReporter  - Table/View 'TESTSCHEMA.EVENT' does not exist.
672109 ["http-bio-8080"-exec-2] ERROR freemarker.runtime  - Method public java.lang.String org.hibernate.exception.NestableRuntimeException.getMessage(int) threw an exception when invoked on org.hibernate.exception.SQLGrammarException: could not execute query
Where do the Event is called from? I have Events in my testschema but not event. Any idea?
Thank you

**Comment by chrishulbert** [comment]
Hi,
Depending on your situation, you may have to make the tables manually. Also,
i may have gotten the name of the table wrong, or you may have configured it
to use an 'event' table instead of 'events'.
Good luck

**Comment by dualboot** [comment]
Oops, my bad, I was missing the annotation mapping for Event to table name Events and Person to table name People. Once I added its all working. I am using Apache Derby DB. So I created the table in a bit different way than the one stated for MS SQL. 

# Here is my Apache Derby tables creation file:

//Note: For Apache Derby SQL database.
//Note: Please replace TESTSCHEMA with your schema name.
CREATE TABLE TESTSCHEMA.EVENT_PERSON
(
    EVENT_ID INT NOT NULL, 
    PERSON_ID INT NOT NULL,
    CONSTRAINT PK_EVENT_PERSON PRIMARY KEY (EVENT_ID, PERSON_ID)
);

CREATE TABLE TESTSCHEMA.EVENTS
(
    ID INT NOT NULL,
    DT DATE, 
    NAME VARCHAR(50),
    CONSTRAINT PK_EVENTS PRIMARY KEY (ID)
);

CREATE TABLE TESTSCHEMA.PEOPLE
(
    ID INT NOT NULL,
    NAME VARCHAR(50) NOT NULL,
    CONSTRAINT PK_PEOPLE PRIMARY KEY (ID)
);

INSERT INTO TESTSCHEMA.EVENTS(ID, DT, NAME)
VALUES (1, '2009-12-31', 'New Years Eve');

INSERT INTO TESTSCHEMA.EVENTS(ID, DT, NAME)
VALUES (2, '2010-1-1', 'New Year Day');

insert into TESTSCHEMA.people(id, name)
values (1, 'John Smith');

insert into TESTSCHEMA.people(id, name)
values (2, 'Jane Doe');

insert into TESTSCHEMA.event_person(event_id,person_id)
select TESTSCHEMA.events.id, TESTSCHEMA.people.id
from TESTSCHEMA.events,TESTSCHEMA.people
where TESTSCHEMA.people.name='Jane Doe';

#

**Comment by dualboot** [comment]
Its a great article and its all works now with my Apache Derby 10.8, Apache Tomcat 7 Server.
Here is my hibernate connection for Derby SQL.



```
    <property name="connection.driver_class">org.apache.derby.jdbc.ClientDriver</property>
    <property name="connection.url">jdbc:derby://localhost:1527/sample;create=true</property>
    <property name="connection.username">user</property>
    <property name="connection.password">password</property>
    <property name="hibernate.default_schema">TESTSCHEMA</property>
```

**Comment by chrishulbert** [comment]
That's fantastic, i'm glad you got it working

**Comment by dualboot** [comment]
Hi Chris - I know what I am going to ask is out of scope of the tutorial.
How ever will you please consider using Generic DAO for the 2 domain models?
So that the new, delete and list all can be generic?
Thank you

**Comment by chrishulbert** [comment]
Hi,
That's not going to happen - i'm not really a java developer any more, i
wrote that tutorial quite a while ago. If you feel like it, you could write
the tutorial!

**Comment by dualboot** [comment]
Chris,

Thank you. I will be honored to be of anyway to update or add as a feedback
to
make generic methods to the 2 models.

Thank you again

Suresh
